# @see https://www.drupal.org/docs/8/api/migrate-api/migrate-destination-plugins-examples/migrating-configuration
id: d7_nagios_static_settings
label: Nagios static configuration
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: variable
  variables:
    - nagios_ignored_modules
    - nagios_ignored_themes
    - nagios_ua
    - nagios_page_path
    - nagios_status_ok_value
    - nagios_status_warning_value
    - nagios_status_critical_value
    - nagios_status_unknown_value
    - nagios_show_outdated_names
    - nagios_enable_status_page
    - nagios_enable_status_page_get

    # nagios_enable_* variables are handled in "d7_nagios_dynamic_settings"

    - nagios_func_watchdog
    - nagios_func_cron
    - nagios_func_session_anon
    - nagios_func_session_auth
    - nagios_func_users
    - nagios_func_modules
    - nagios_func_themes
    - nagios_func_requirements

    - limit_watchdog_display
    - nagios_min_report_severity
    - nagios_cron_duration
    - nagios_elysia_cron_duration
  source_module: nagios
process:
  nagios/ignored_modules: nagios_ignored_modules
  nagios/ignored_themes: nagios_ignored_themes
  nagios/ua: nagios_ua
  nagios/statuspage/path: nagios_page_path
  nagios/status/ok: nagios_status_ok_value
  nagios/status/warning: nagios_status_warning_value
  nagios/status/critical: nagios_status_critical_value
  nagios/status/unknown: nagios_status_unknown_value
  nagios/show_outdated_names: nagios_show_outdated_names
  nagios/statuspage/enabled: nagios_enable_status_page
  nagios/statuspage/getparam: nagios_enable_status_page_get

  nagios/function/watchdog: nagios_func_watchdog
  nagios/function/cron: nagios_func_cron
  nagios/function/session_anon: nagios_func_session_anon
  nagios/function/session_auth: nagios_func_session_auth
  nagios/function/users: nagios_func_users
  nagios/function/modules: nagios_func_modules
  nagios/function/themes: nagios_func_themes
  nagios/function/requirements: nagios_func_requirements

  nagios/limit_watchdog/display: limit_watchdog_display
  nagios/min_report_severity: nagios_min_report_severity
  nagios/cron_duration: nagios_cron_duration
  nagios/elysia_cron_duration: nagios_elysia_cron_duration
destination:
  plugin: config
  config_name: nagios.settings
