id: d7_nagios_dynamic_settings
label: Nagios dynamic configuration
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: nagios_dynamic_variables_source
  source_module: nagios
destination:
  plugin: config
  config_name: nagios.settings
