<?php

//Ensure this module is called last by the node_presave hook
function rii_region_module_implements_alter(&$implementations, $hook) {
  switch($hook) {
    case 'entity_presave':
      $group = $implementations['rii_region'];
      unset($implementations['rii_region']);
      $implementations['rii_region'] = $group;
      break;
  }
}


function rii_region_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->bundle() == "rii") { //If content type is RII
    $postcode = $entity->get('field_q_6a')->postal_code;
    $postcode = str_split($postcode);
    //Get post code area (first 1-3 letters)
    foreach ($postcode as $key => $value) {
      if (strval($value) === strval(intval($value))) {
          $postcode_area = implode(array_slice($postcode, 0, $key));
          //Look-up region of post code area in DB table region_lookup
          $connection = \Drupal::database();
          $region = $connection->query("SELECT region_name FROM region_lookup WHERE region_prefix = '$postcode_area'");
          $entity->field_q_6a->locality = $region->fetchField(0); 
          break;
      }
    }

  }
}
